#!/usr/bin/env python
# coding: utf-8

# # Assignment 1: Recursion

# ##### Student Name: Mitra Rokni
# ##### Deadline: Friday September 11th

# ## 04: Calculate specific character in a given string

# In[1]:


def CountChar(string, char):
    if not string:
        return 0
    else:
        return (string[0] == char) + CountChar(string[1:], char)


# In[2]:


string = "jogging"
char = "j"
print(CountChar(string, char))


# In[3]:


#4 second solution 
def findNr(s,ch, count=0):
    if s== '':
        return count
    else:
        if s[0]== ch:
            count = count+1
        return findNr(s[1:], ch , count )
        
        
s="my name is  mm mm mitra"
ch='m'
print(findNr(s,ch))


# ## 05: Power of

# In[12]:


def Pow(n, m):
    if (m == 0):
        return 1
    else:
        return n * Pow(n, m-1)   


# In[28]:


n, m = 2, 5
print(Pow(n, m))


# ## 06: Multiplication of integers

# In[7]:


def Mul(n, m):
    if (m == 0):
        return 0
    elif (m == 1):
        return n
    else:
        return n + Mul(n, m-1)


# In[8]:


n, m = 2, 5
print(Mul(n, m))


# ## 08: Harmonic sum

# In[9]:


def Harmonic(n):
    if (n == 1):
        return 1
    else:
        return (1 / n) + Harmonic(n-1)


# In[10]:


n = 2
print(Harmonic(n))


# ## 09: Largest value in a list

# In[ ]:


# first 
def Large(list):
    if len(list) == 1:
        return list[0]
    else:
        return list[0] if list[0] > Large(list[1:]) else Large(list[1:])
    
list = [1, 2, 3, 4, 5]
print(Large(list))    


# In[ ]:


#9 second way:
def large_value(list):
    if len(list) == 1:
        return list[0]
    else:
        big = large_value(list[1:])
        if list[0] > big:
            return list[0]
        else:
            return big

        
list = [2,44,5,0]
print(large_value(list))


# ## 10: Reverse order

# In[ ]:


def Reverse(string):
    if not string:
        return ""
    else:
        return string[-1] + Reverse(string[:-1])


# In[5]:


string = "sample string"
print(Reverse(string))


# ## 14: Matching parentheses

# In[19]:



def Match(string, counter = 0):
    if not string:
        return (counter == 0)
    if (counter > 0):
        return False
    if string[-1] == ")":
        return Match(string[:-1], counter-1)
    elif string[-1] == "(":
        return Match(string[:-1], counter+1)
    else:
        return Match(string[:-1], counter)


# In[20]:


string = "((((()))))"
print(Match(string))

string = "(()))))"
print(Match(string))


# In[ ]:



def Match(string):
    s = Stack()
    balanced = True
    index = 0
    if not string:
        return list
    if (stack= 0):
        return False
    if string[-1] ==`````````````````````````````````````` ")":
        return Match(string[:-1], counter-1)
    elif string[-1] == "(":
        return Match(string[:-1], counter+1)
    else:
        return Match(string[:-1], counter)


# ## 15 : Algorithm Analysis tasks

# In[3]:


# 03: Time to calculate Fibonacci sequence
import time
def fib(n):
    if n in (0,1) :
        return n 
    else: 
        return fib(n-1)+fib(n-2)
time.time()


# In[10]:


# 03: Time to calculate Fibonacci sequence

def fib(n):
    if n in (0,1) :
        return n 
    else: 
        return fib(n-1)+fib(n-2)

print(fib(35))

# with watch      8.093= c* 1.618^35

      
# In[18]:


print(pow(1.618,35))
print(8.093/20618074.50599988)


# In[17]:


# t(50)= 545081.062694147 * 1.618^50
#t(100)= 545081.062694147* 1.618^100
n=1.618 
m=50
m=100
print(pow(n,m)* 545081.062694147)
m=100
print(pow(n,m)*545081.062694147)


# In[38]:


#05: Insertion sort
def sortIns(l,n):
    if(n>1):
        sortIns(1,n-1)
        x= 1[n-1]
        i=n-2
        while(i>=0 and l[i]<x):
            l[i+1]=l[i]
            i=i-1
        l[i+1]=x
    
n=5
l=[2,7,4,5,61,22,34]
# the answer of this book is in the word-version file


# In[ ]:


# 06: Compare insertion and merge sort
# the answer of this book is in the word-version file

